### 주문
POST http://localhost:8080/v1/orders
Content-Type: application/json

{
  "customerId": 1,
  "orderItems": [
    {
      "productId": "1743312828636_3e2c670b-6067-4885-a885-91d9b309e175",
      "quantity": 2
    }
  ],
  "paymentMethod": "CREDIT_CARD"
}

### 결제 완료
POST http://localhost:8080/v1/orders/1011613/payment
Content-Type: application/json

{
  "success": true
}

### 결제 실패
POST http://localhost:8080/v1/orders/1/payment
Content-Type: application/json

{
  "success": false
}

### 주문 완료
POST http://localhost:8080/v1/orders/1011613/complete
Content-Type: application/json


### 주문 취소
POST http://localhost:8080/v1/orders/1011613/cancel
Content-Type: application/json
